CREATE TABLE activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(32) NOT NULL CHECK (type IN (
        'tarea_completada',
        'habito_cumplido',
        'nota_creada',
        'adjunto_subido',
        'tarea_desmarcada',
        'habito_desmarcado',
        'habito_pospuesto'
    )),
    element_legacy_id BIGINT CHECK (element_legacy_id IS NULL OR element_legacy_id > 0),
    element_type VARCHAR(16) CHECK (element_type IS NULL OR element_type IN ('tarea', 'habito', 'nota', 'proyecto')),
    project_legacy_id BIGINT CHECK (project_legacy_id IS NULL OR project_legacy_id > 0),
    date DATE NOT NULL,
    local_time TIME,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_activity_events_user_date
    ON activity_events(user_id, date DESC, id DESC);
CREATE INDEX idx_activity_events_user_type_date
    ON activity_events(user_id, type, date DESC);
CREATE INDEX idx_activity_events_user_project_date
    ON activity_events(user_id, project_legacy_id, date DESC)
    WHERE project_legacy_id IS NOT NULL;
CREATE INDEX idx_activity_events_user_element_date
    ON activity_events(user_id, element_type, element_legacy_id, date DESC)
    WHERE element_legacy_id IS NOT NULL;

CREATE UNIQUE INDEX ux_activity_events_habit_completed_day
    ON activity_events(user_id, element_legacy_id, date, type)
    WHERE element_type = 'habito' AND type = 'habito_cumplido';
